#!/bin/bash -x
# put the data into a couchdb
ipaddr="192.168.123.11"
user_pass="admin:admin"
dbname="testlog"

# fetch the ini settings for this unit under test
declare -A settings=`cat xsce.ini.map`

curl --user $user_pass -vX PUT http://$ipaddr:5984/dbname ${["version_xsce_uuid"]} -d @`cat testresults`
