#!/bin/bash -x

# copy some files to test xsce

mkdir /root/testing
cp /media/testing/root/* /root/testing
chmod 755 /root/testing/*

# put a large marker on the screen that is easily checked for
echo ""
echo "           ********************************************"
echo "           *                                          *"
echo "           *  Good, bon, bueno install was successful *"
echo "           *                                          *"
echo "           ********************************************"
